"""Unified proposal, baseline, and attack package for watermarking research."""

from .proposals import (
    QR64Config,
    QR64Key,
    DirectSchurRescueConfig,
    DirectSchurRescueKey,
    CDDetQRConfig,
    CDDetQRKey,
    BlindCDDetQR,
    ABLATION_FLAGS,
    HYPERPARAMETER_FLAGS,
    apply_proposal_flags,
    DCT_QR,
    DCT_SCHUR_RESCUE,
    SPATIAL_CD_DETQR,
    QR_CERTIFIED,
    DIRECT_SCHUR_RESCUE,
    embed,
    extract,
    embed_proposal,
    extract_proposal,
    list_supported_methods,
    normalize_proposal_method_id,
)
from .baselines import (
    ALL_BASELINE_IDS,
    PRIMARY_BLIND_BASELINE_IDS,
    embed_baseline,
    extract_baseline,
    list_baselines,
)

__all__ = [
    "QR64Config",
    "QR64Key",
    "DirectSchurRescueConfig",
    "DirectSchurRescueKey",
    "CDDetQRConfig",
    "CDDetQRKey",
    "BlindCDDetQR",
    "ABLATION_FLAGS",
    "HYPERPARAMETER_FLAGS",
    "apply_proposal_flags",
    "DCT_QR",
    "DCT_SCHUR_RESCUE",
    "SPATIAL_CD_DETQR",
    "QR_CERTIFIED",
    "DIRECT_SCHUR_RESCUE",
    "embed",
    "extract",
    "embed_proposal",
    "extract_proposal",
    "list_supported_methods",
    "normalize_proposal_method_id",
    "ALL_BASELINE_IDS",
    "PRIMARY_BLIND_BASELINE_IDS",
    "embed_baseline",
    "extract_baseline",
    "list_baselines",
]
